// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUEPDiyzazM-0N-623EdG7yFkEMQwyWNA',
    appId: '1:252597819762:web:b738cc17ca50b3758ba5eb',
    messagingSenderId: '252597819762',
    projectId: 'money-tracker-together',
    authDomain: 'money-tracker-together.firebaseapp.com',
    storageBucket: 'money-tracker-together.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqU_ZYq68mIZtY6U6uIfQbRlmNlxnis-E',
    appId: '1:252597819762:android:6068f2bc148008898ba5eb',
    messagingSenderId: '252597819762',
    projectId: 'money-tracker-together',
    storageBucket: 'money-tracker-together.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbm_5eghCtL3e4PYlYI5ym_nkRAYUTQ_E',
    appId: '1:252597819762:ios:6886043096322ccf8ba5eb',
    messagingSenderId: '252597819762',
    projectId: 'money-tracker-together',
    storageBucket: 'money-tracker-together.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackerTogether',
  );
}
